# Озеро даних: Bronze → Silver → Gold

Конвеєр обробки даних мережі станцій моніторингу якості повітря.
Джерело - контейнер `data-lake` (3 сирі JSON), результат - власний префікс `shudria_oleh/` у контейнері `students-homework`.

## Налаштування та функції

Імпорти, SAS-доступи, константи й допоміжні функції для роботи з джерелом та озером.

In [1]:
# завантаження бібліотек
from azure.storage.blob import ContainerClient
from io import BytesIO
import pandas as pd
from datetime import datetime, timezone
import pyarrow
import json

In [2]:
# Джерело (тільки читання)
SOURCE_SAS = "https://datalakedatalab.blob.core.windows.net/data-lake?sp=r&st=2026-07-16T08:11:59Z&se=2026-08-31T16:26:59Z&spr=https&sv=2026-02-06&sr=c&sig=JHmTjds1p8Rp%2Bn9nXZUSWSMdkgAkuPdz%2B4KjbAQUlX0%3D"

In [3]:
# Озеро (читання + запис)
LAKE_SAS = "https://datalakedatalab.blob.core.windows.net/students-homework?sp=racwl&st=2026-07-16T08:10:00Z&se=2026-08-31T16:25:00Z&spr=https&sv=2026-02-06&sr=c&sig=wCRv3poEsB8L4%2Bnj3BKZvwcvlX9vGJ5xo93jYaG3no4%3D"

In [4]:
source = ContainerClient.from_container_url(SOURCE_SAS)
lake   = ContainerClient.from_container_url(LAKE_SAS)

STUDENT = "shudria_oleh"
TABLES = ["stations", "sensors", "readings"]
ZONES = ["bronze", "silver", "gold"]

# створюємо єдину мітку часу для всіх записів у озері (batch timestamp)
INGESTED_AT_UTC = datetime.now(timezone.utc)

# журнал якості даних: наповнюється під час очищення в Silver
QUALITY_LOG = []

def log_drop(table, reason, before, after):
    """Записує в журнал, скільки рядків відкинув один етап очищення."""
    QUALITY_LOG.append({
        "table": table,
        "reason": reason,
        "rows_before": before,
        "rows_dropped": before - after,
        "rows_after": after,
    })

# Шаблон імені файлу у джерелі
def source_filename(table):
    return f"{table}.json"

# Шаблон читання JSON із джерела
def read_source_json(table):
    name = source_filename(table)
    raw = source.download_blob(name).readall()
    return pd.read_json(BytesIO(raw), dtype=str, convert_dates=False)

# Шаблон шляху до файлу у озері
def lake_path(zone, table):
    return f"{STUDENT}/{zone}/{table}/{table}.parquet"

# Шаблон запису DataFrame у Parquet в озеро
def write_parquet(df, zone, table):
    buf = BytesIO()
    df.to_parquet(buf, index=False)
    buf.seek(0)

    lake.upload_blob(
        name=lake_path(zone, table),
        data=buf.getvalue(),
        overwrite=True
    )

# Шаблон читання Parquet із озера
def read_lake_parquet(zone, table):
    blob = lake.download_blob(lake_path(zone, table)).readall()
    return pd.read_parquet(BytesIO(blob), engine="pyarrow")

# Крок 1. Bronze

Сира копія джерела без жодного очищення. Єдине доповнення - два технічні поля: `_ingested_at` (мітка партії завантаження) і `_source_file` (звідки взято дані).

## Перевірка джерела

SAS джерела має лише `sp=r` (без `l`), тому `list_blobs()` недоступний - перевіряємо файли за відомими іменами.

In [5]:
# Перевірка файлів: що лежать у джерелі
for table in TABLES:
    props = source.get_blob_client(source_filename(table)).get_blob_properties()
    print(source_filename(table), props.size, props.last_modified)

stations.json 996 2026-07-16 08:24:29+00:00
sensors.json 833 2026-07-16 08:24:29+00:00
readings.json 3233 2026-07-16 08:24:29+00:00

## Завантаження

Читаємо JSON як текст (`dtype=str`, `convert_dates=False`), щоб pandas не «виправив» сирі значення, додаємо технічні поля й складаємо все у словник `dfs`.

In [6]:
def load_source_tables():
    storage = {}
    for table in TABLES:
        df = read_source_json(table)
        # додаємо колонки для озера
        df["_ingested_at"] = INGESTED_AT_UTC
        df["_source_file"] = source_filename(table)

        # додаємо датафрейм у словник
        storage[table] = df
    return storage

In [7]:
dfs = load_source_tables()
dfs.keys()

dict_keys(['stations', 'sensors', 'readings'])

In [8]:
for name, df in dfs.items():
    print(name, df.shape)

stations (7, 7)
sensors (8, 6)
readings (23, 7)

In [9]:
dfs["stations"]

,station_id,name,city,country,installed_at,_ingested_at,_source_file
0,ST01,Центр,Київ,UA,2024-05-10,2026-07-27 20:06:43.256724+00:00,stations.json
1,ST02,Оболонь,Kyiv,Ukraine,2024/06/01,2026-07-27 20:06:43.256724+00:00,stations.json
2,ST03,Личаків,Львів,україна,2024.06.15,2026-07-27 20:06:43.256724+00:00,stations.json
3,ST04,Stare Miasto,Kraków,PL,10/07/2024,2026-07-27 20:06:43.256724+00:00,stations.json
4,ST05,Centrum,Warsaw,Poland,NaN,2026-07-27 20:06:43.256724+00:00,stations.json
5,ST06,Позняки,KYIV,UA,2024-08-20,2026-07-27 20:06:43.256724+00:00,stations.json
6,ST03,Личаків,Львів,UA,2024-06-15,2026-07-27 20:06:43.256724+00:00,stations.json

In [10]:
dfs["sensors"]

,sensor_id,station_id,metric,unit,_ingested_at,_source_file
0,SN100,ST01,PM2.5,µg/m3,2026-07-27 20:06:43.256724+00:00,sensors.json
1,SN101,ST01,CO2,ppm,2026-07-27 20:06:43.256724+00:00,sensors.json
2,SN102,ST02,pm2_5,ug/m3,2026-07-27 20:06:43.256724+00:00,sensors.json
3,SN103,ST03,PM 2.5,µg/m3,2026-07-27 20:06:43.256724+00:00,sensors.json
4,SN104,ST03,temperature,°C,2026-07-27 20:06:43.256724+00:00,sensors.json
5,SN105,ST04,PM10,µg/m3,2026-07-27 20:06:43.256724+00:00,sensors.json
6,SN106,ST05,humidity,%,2026-07-27 20:06:43.256724+00:00,sensors.json
7,SN107,ST06,PM2.5,NaN,2026-07-27 20:06:43.256724+00:00,sensors.json

In [11]:
dfs["readings"]

,reading_id,sensor_id,value,measured_at,status,_ingested_at,_source_file
0,R0001,SN100,23.4,2026-07-01 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
1,R0002,SN100,"31,7",2026-07-01 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json
2,R0003,SN101,610,01/07/2026 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
3,R0004,SN102,18.9,2026.07.01 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
4,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
5,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
6,R0006,SN104,27.5,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
7,R0007,SN100,-3,2026-07-02 08:00,error,2026-07-27 20:06:43.256724+00:00,readings.json
8,R0008,SN105,52.0,2026-07-02 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
9,R0009,SN106,64,02/07/2026 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
10,R0010,SN101,NaN,2026-07-02 12:00,calibrating,2026-07-27 20:06:43.256724+00:00,readings.json
11,R0011,SN102,22.1,2026-07-02 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json
12,R0012,SN100,5000,2026-07-03 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
13,R0013,SN103,38.6,2026-07-03 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
14,R0014,SN999,40.0,2026-07-03 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
15,R0015,SN105,"49,8",2026-07-03 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
16,R0016,SN104,29.1,NaN,ok,2026-07-27 20:06:43.256724+00:00,readings.json
17,R0017,SN100,26.3,2026-07-04 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
18,R0018,SN106,71,2026-07-04 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
19,R0019,SN102,20.4,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
20,R0020,SN101,720,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
21,R0021,SN103,41.0,04/07/2026 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
22,R0022,SN105,55.7,2026-07-05 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json

## Розвідка: що не так із даними

Оглядаємо дані, щоб скласти план очищення для Silver. Тут нічого не змінюємо - Bronze лишається сирим.

In [12]:
dfs["readings"].dtypes

reading_id                      str
sensor_id                       str
value                           str
measured_at                     str
status                          str
_ingested_at    datetime64[us, UTC]
_source_file                    str
dtype: object

In [13]:
dfs["sensors"]["metric"].value_counts()

metric
PM2.5          2
CO2            1
pm2_5          1
PM 2.5         1
temperature    1
PM10           1
humidity       1
Name: count, dtype: int64

In [14]:
dfs["readings"]["status"].value_counts()

status
ok             19
OK              2
error           1
calibrating     1
Name: count, dtype: int64

In [15]:
dfs["readings"]["value"].unique()

<ArrowStringArray>
['23.4', '31,7',  '610', '18.9', '45.2', '27.5',   '-3', '52.0',   '64',
    nan, '22.1', '5000', '38.6', '40.0', '49,8', '29.1', '26.3',   '71',
 '20.4',  '720', '41.0', '55.7']
Length: 22, dtype: str

## Запис в озеро

Зберігаємо всі три таблиці у `bronze/` у форматі Parquet. `overwrite=True` робить повторний запуск безпечним - файли замінюються, а не дублюються.

In [16]:
for name, df in dfs.items():
    write_parquet(df, "bronze", name)

## Перевірка

Round-trip: читаємо записане назад і порівнюємо з оригіналом через `.equals()`, потім дивимось на вміст своєї папки в озері.

In [17]:
for name in dfs.keys():
    print(f"{name}: {dfs[name].equals(read_lake_parquet('bronze', name))}")

stations: True
sensors: True
readings: True

In [18]:
for b in lake.list_blobs(name_starts_with=STUDENT):
    print(b.name, b.size, b.last_modified)

shudria_oleh/bronze/readings/readings.parquet 4963 2026-07-27 20:06:44+00:00
shudria_oleh/bronze/sensors/sensors.parquet 4073 2026-07-27 20:06:44+00:00
shudria_oleh/bronze/stations/stations.parquet 4760 2026-07-27 20:06:44+00:00
shudria_oleh/gold/avg_by_city_metric/avg_by_city_metric.parquet 2956 2026-07-27 20:02:50+00:00
shudria_oleh/gold/daily_trend/daily_trend.parquet 2529 2026-07-27 20:02:50+00:00
shudria_oleh/gold/pm25_exceedances/pm25_exceedances.parquet 2903 2026-07-27 20:02:50+00:00
shudria_oleh/silver/_quality_report.json 1550 2026-07-27 20:02:50+00:00
shudria_oleh/silver/_tier_probe.json 208 2026-07-27 19:59:59+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=01/part.parquet 4535 2026-07-27 20:02:49+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=02/part.parquet 4474 2026-07-27 20:02:49+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=03/part.parquet 4486 2026-07-27 20:02:49+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=04/part.parquet 4524 2026-07-27 20:02:50+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=05/part.parquet 4425 2026-07-27 20:02:50+00:00
shudria_oleh/silver/sensors/sensors.parquet 2773 2026-07-27 20:02:49+00:00
shudria_oleh/silver/stations/stations.parquet 3441 2026-07-27 20:02:49+00:00
shudria_oleh/stations/stations.parquet 4724 2026-07-26 14:22:36+00:00

> **Примітка про артефакти.** У власному префіксі є два блоби поза структурою зон:
> `shudria_oleh/stations/stations.parquet` (запис із помилковим шляхом на ранньому етапі, без сегмента `bronze/`) і
> `shudria_oleh/silver/_tier_probe.json` (разова перевірка доступу).
> Видалити їх неможливо: SAS озера має `sp=racwl`, дозволу `d` (Delete) немає. Обидва не використовуються конвеєром.

## Знайдені проблеми - план для Silver

| Таблиця | Проблема | Приклад |
|---|---|---|
| stations | різні формати дат | `2024/06/01`, `2024.06.15`, `10/07/2024` |
| stations | пропущена дата | рядок 4 |
| stations | різні назви країни | `UA`, `Ukraine`, `україна`, `PL`, `Poland` |
| stations | різний регістр міста | `Київ`, `Kyiv`, `KYIV` |
| stations | дублікат `ST03` | рядки 2 і 6, різні `country` |
| sensors | три написання метрики | `PM2.5`, `pm2_5`, `PM 2.5` |
| sensors | два написання одиниці | `µg/m3`, `ug/m3` |
| sensors | пропущена одиниця | `SN107` |
| readings | десяткова кома | `31,7`, `49,8` |
| readings | три формати дат | `01/07/2026`, `2026.07.01` |
| readings | регістр статусу | `ok` / `OK` |
| readings | повний дублікат | `R0005` |
| readings | осиротілий `sensor_id` | `SN999` (немає в `sensors`) |
| readings | від'ємне значення | `-3` |
| readings | аномалія при статусі `ok` | `5000` |
| readings | пропуски | `value`, `measured_at` |

# Крок 2. Silver

Очищені й типізовані дані: приведення типів, розбір дат, нормалізація назв, видалення дублікатів і відсів аномалій за списком вище.

## 2.1. Таблиця stations

Читаємо `stations` із Bronze. Нормалізуємо `city` і `country` за словниками, дати розбираємо каскадом із двох явних форматів: спершу `%Y-%m-%d`, потім `%d-%m-%Y` для рядків, що лишились порожніми.

Дедуплікація за `station_id` виконується **після** нормалізації: тоді обидва записи `ST03` стають ідентичними, і питання «який рядок залишити» зникає само.

In [19]:
df_stations_silver = read_lake_parquet("bronze", "stations")
df_stations_silver

,station_id,name,city,country,installed_at,_ingested_at,_source_file
0,ST01,Центр,Київ,UA,2024-05-10,2026-07-27 20:06:43.256724+00:00,stations.json
1,ST02,Оболонь,Kyiv,Ukraine,2024/06/01,2026-07-27 20:06:43.256724+00:00,stations.json
2,ST03,Личаків,Львів,україна,2024.06.15,2026-07-27 20:06:43.256724+00:00,stations.json
3,ST04,Stare Miasto,Kraków,PL,10/07/2024,2026-07-27 20:06:43.256724+00:00,stations.json
4,ST05,Centrum,Warsaw,Poland,NaN,2026-07-27 20:06:43.256724+00:00,stations.json
5,ST06,Позняки,KYIV,UA,2024-08-20,2026-07-27 20:06:43.256724+00:00,stations.json
6,ST03,Личаків,Львів,UA,2024-06-15,2026-07-27 20:06:43.256724+00:00,stations.json

In [20]:
CITY_MAP = {
    "Київ": "Kyiv",
    "Kyiv": "Kyiv",
    "KYIV": "Kyiv",
    "Львів": "Lviv",
    "Lviv": "Lviv",
    "LVIV": "Lviv",
    "Kraków": "Kraków",
    "Warsaw": "Warsaw",
}

COUNTRY_MAP = {
    "UA": "UA",
    "Ukraine": "UA",
    "україна": "UA",
    "PL": "PL",
    "Poland": "PL",
}

In [21]:
# нормалізація даних
df_stations_silver["city_normalized"] = df_stations_silver["city"].replace(CITY_MAP)
df_stations_silver["country_normalized"] = df_stations_silver["country"].replace(COUNTRY_MAP)

df_stations_silver["installed_at_normalized1"] = pd.to_datetime(
    df_stations_silver["installed_at"].str.replace(r"[/.]", "-", regex=True),
    format="%Y-%m-%d",
    errors="coerce"
)

df_stations_silver["installed_at_normalized2"] = pd.to_datetime(
    df_stations_silver["installed_at"].str.replace(r"[/.]", "-", regex=True),
    format="%d-%m-%Y",
    errors="coerce"
)

df_stations_silver["installed_at_normalized"] = df_stations_silver["installed_at_normalized1"].fillna(df_stations_silver["installed_at_normalized2"])

df_stations_silver

,station_id,name,city,country,installed_at,_ingested_at,_source_file,city_normalized,country_normalized,installed_at_normalized1,installed_at_normalized2,installed_at_normalized
0,ST01,Центр,Київ,UA,2024-05-10,2026-07-27 20:06:43.256724+00:00,stations.json,Kyiv,UA,2024-05-10,NaT,2024-05-10
1,ST02,Оболонь,Kyiv,Ukraine,2024/06/01,2026-07-27 20:06:43.256724+00:00,stations.json,Kyiv,UA,2024-06-01,NaT,2024-06-01
2,ST03,Личаків,Львів,україна,2024.06.15,2026-07-27 20:06:43.256724+00:00,stations.json,Lviv,UA,2024-06-15,NaT,2024-06-15
3,ST04,Stare Miasto,Kraków,PL,10/07/2024,2026-07-27 20:06:43.256724+00:00,stations.json,Kraków,PL,NaT,2024-07-10,2024-07-10
4,ST05,Centrum,Warsaw,Poland,NaN,2026-07-27 20:06:43.256724+00:00,stations.json,Warsaw,PL,NaT,NaT,NaT
5,ST06,Позняки,KYIV,UA,2024-08-20,2026-07-27 20:06:43.256724+00:00,stations.json,Kyiv,UA,2024-08-20,NaT,2024-08-20
6,ST03,Личаків,Львів,UA,2024-06-15,2026-07-27 20:06:43.256724+00:00,stations.json,Lviv,UA,2024-06-15,NaT,2024-06-15

In [22]:
df_stations_silver = df_stations_silver[["station_id", "name", "city_normalized", "country_normalized", "installed_at_normalized"]]

df_stations_silver = df_stations_silver.rename(
    columns={
        "city_normalized": "city",
        "country_normalized": "country",
        "installed_at_normalized": "installed_at",
    }
)

_before = len(df_stations_silver)
df_stations_silver = df_stations_silver.drop_duplicates(subset=["station_id"])
df_stations_silver = df_stations_silver.reset_index(drop=True)
log_drop("stations", "дублікати за station_id", _before, len(df_stations_silver))

df_stations_silver

  station_id          name    city country installed_at
0       ST01         Центр    Kyiv      UA   2024-05-10
1       ST02       Оболонь    Kyiv      UA   2024-06-01
2       ST03       Личаків    Lviv      UA   2024-06-15
3       ST04  Stare Miasto  Kraków      PL   2024-07-10
4       ST05       Centrum  Warsaw      PL          NaT
5       ST06       Позняки    Kyiv      UA   2024-08-20

> **Примітка.** Технічні поля `_ingested_at` і `_source_file` не переносяться в Silver: схема виходу в завданні їх не передбачає.

In [23]:
df_stations_silver.dtypes        # чи справді installed_at став датою

station_id                 str
name                       str
city                       str
country                    str
installed_at    datetime64[us]
dtype: object

In [24]:
df_stations_silver["city"].unique()

<ArrowStringArray>
['Kyiv', 'Lviv', 'Kraków', 'Warsaw']
Length: 4, dtype: str

In [25]:
df_stations_silver["country"].unique()

<ArrowStringArray>
['UA', 'PL']
Length: 2, dtype: str

In [26]:
write_parquet(df_stations_silver, "silver", "stations")

print(f"stations: {df_stations_silver.equals(read_lake_parquet('silver', 'stations'))}")

stations: True

In [27]:
for b in lake.list_blobs(name_starts_with=STUDENT):
    print(b.name, b.size, b.last_modified)

shudria_oleh/bronze/readings/readings.parquet 4963 2026-07-27 20:06:44+00:00
shudria_oleh/bronze/sensors/sensors.parquet 4073 2026-07-27 20:06:44+00:00
shudria_oleh/bronze/stations/stations.parquet 4760 2026-07-27 20:06:44+00:00
shudria_oleh/gold/avg_by_city_metric/avg_by_city_metric.parquet 2956 2026-07-27 20:02:50+00:00
shudria_oleh/gold/daily_trend/daily_trend.parquet 2529 2026-07-27 20:02:50+00:00
shudria_oleh/gold/pm25_exceedances/pm25_exceedances.parquet 2903 2026-07-27 20:02:50+00:00
shudria_oleh/silver/_quality_report.json 1550 2026-07-27 20:02:50+00:00
shudria_oleh/silver/_tier_probe.json 208 2026-07-27 19:59:59+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=01/part.parquet 4535 2026-07-27 20:02:49+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=02/part.parquet 4474 2026-07-27 20:02:49+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=03/part.parquet 4486 2026-07-27 20:02:49+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=04/part.parquet 4524 2026-07-27 20:02:50+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=05/part.parquet 4425 2026-07-27 20:02:50+00:00
shudria_oleh/silver/sensors/sensors.parquet 2773 2026-07-27 20:02:49+00:00
shudria_oleh/silver/stations/stations.parquet 3441 2026-07-27 20:06:44+00:00
shudria_oleh/stations/stations.parquet 4724 2026-07-26 14:22:36+00:00

## 2.2. Таблиця sensors

Читаємо `sensors` із Bronze. Метрики зводимо до п'яти канонічних значень, написання одиниць уніфікуємо (`ug/m3` до `µg/m3`), пропущені одиниці заповнюємо за метрикою.

Заповнення працює через `fillna`, тобто спрацьовує **тільки там, де порожньо**: наявні значення з джерела не перезаписуються, і розбіжність «метрика проти одиниці» лишилась би помітною.

Дві перевірки різної природи: `station_id` звіряємо з Silver-версією `stations` (якість джерела), а перелік метрик з ключами `UNIT_MAP` (повнота власного словника).

In [28]:
df_sensors_silver = read_lake_parquet("bronze", "sensors")
df_sensors_silver

,sensor_id,station_id,metric,unit,_ingested_at,_source_file
0,SN100,ST01,PM2.5,µg/m3,2026-07-27 20:06:43.256724+00:00,sensors.json
1,SN101,ST01,CO2,ppm,2026-07-27 20:06:43.256724+00:00,sensors.json
2,SN102,ST02,pm2_5,ug/m3,2026-07-27 20:06:43.256724+00:00,sensors.json
3,SN103,ST03,PM 2.5,µg/m3,2026-07-27 20:06:43.256724+00:00,sensors.json
4,SN104,ST03,temperature,°C,2026-07-27 20:06:43.256724+00:00,sensors.json
5,SN105,ST04,PM10,µg/m3,2026-07-27 20:06:43.256724+00:00,sensors.json
6,SN106,ST05,humidity,%,2026-07-27 20:06:43.256724+00:00,sensors.json
7,SN107,ST06,PM2.5,NaN,2026-07-27 20:06:43.256724+00:00,sensors.json

In [29]:
df_sensors_silver["metric"].unique()

<ArrowStringArray>
['PM2.5', 'CO2', 'pm2_5', 'PM 2.5', 'temperature', 'PM10', 'humidity']
Length: 7, dtype: str

In [30]:
df_sensors_silver["unit"].unique()

<ArrowStringArray>
['µg/m3', 'ppm', 'ug/m3', '°C', '%', nan]
Length: 6, dtype: str

In [31]:
METRIC_MAP = {
    "PM2.5": "PM2.5",
    "pm2_5": "PM2.5",
    "PM 2.5": "PM2.5",
    "PM10": "PM10",
    "CO2": "CO2",
    "temperature": "temperature",
    "humidity": "humidity",
}

UNIT_MAP = {
    "PM2.5": "µg/m3",
    "PM10": "µg/m3",
    "CO2": "ppm",
    "temperature": "°C",
    "humidity": "%",
}

UNIT_SPELLING_MAP = {
    "ug/m3": "µg/m3",
}

In [32]:
df_sensors_silver["metric_normalized"] = df_sensors_silver["metric"].replace(METRIC_MAP)
df_sensors_silver["unit_normalized"] = df_sensors_silver["unit"].replace(UNIT_SPELLING_MAP).fillna(df_sensors_silver["metric_normalized"].map(UNIT_MAP))
df_sensors_silver

,sensor_id,station_id,metric,unit,_ingested_at,_source_file,metric_normalized,unit_normalized
0,SN100,ST01,PM2.5,µg/m3,2026-07-27 20:06:43.256724+00:00,sensors.json,PM2.5,µg/m3
1,SN101,ST01,CO2,ppm,2026-07-27 20:06:43.256724+00:00,sensors.json,CO2,ppm
2,SN102,ST02,pm2_5,ug/m3,2026-07-27 20:06:43.256724+00:00,sensors.json,PM2.5,µg/m3
3,SN103,ST03,PM 2.5,µg/m3,2026-07-27 20:06:43.256724+00:00,sensors.json,PM2.5,µg/m3
4,SN104,ST03,temperature,°C,2026-07-27 20:06:43.256724+00:00,sensors.json,temperature,°C
5,SN105,ST04,PM10,µg/m3,2026-07-27 20:06:43.256724+00:00,sensors.json,PM10,µg/m3
6,SN106,ST05,humidity,%,2026-07-27 20:06:43.256724+00:00,sensors.json,humidity,%
7,SN107,ST06,PM2.5,NaN,2026-07-27 20:06:43.256724+00:00,sensors.json,PM2.5,µg/m3

In [33]:
df_sensors_silver = df_sensors_silver[["sensor_id", "station_id", "metric_normalized", "unit_normalized"]]
df_sensors_silver = df_sensors_silver.rename(
    columns={
        "metric_normalized": "metric",
        "unit_normalized": "unit"
    }
)
df_sensors_silver

  sensor_id station_id       metric   unit
0     SN100       ST01        PM2.5  µg/m3
1     SN101       ST01          CO2    ppm
2     SN102       ST02        PM2.5  µg/m3
3     SN103       ST03        PM2.5  µg/m3
4     SN104       ST03  temperature     °C
5     SN105       ST04         PM10  µg/m3
6     SN106       ST05     humidity      %
7     SN107       ST06        PM2.5  µg/m3

In [34]:
df_stations_silver_ref = read_lake_parquet("silver", "stations")
station_ids = set(df_stations_silver_ref["station_id"])
station_ids

{'ST01', 'ST02', 'ST03', 'ST04', 'ST05', 'ST06'}

In [35]:
missing_station_ids = set(df_sensors_silver["station_id"].unique()) - station_ids
missing_station_ids

set()

In [36]:
filter_stations = df_sensors_silver["station_id"].isin(station_ids)

_before = len(df_sensors_silver)
df_sensors_silver = df_sensors_silver[filter_stations].reset_index(drop=True)
log_drop("sensors", "station_id відсутній у Silver-таблиці stations", _before, len(df_sensors_silver))

df_sensors_silver

  sensor_id station_id       metric   unit
0     SN100       ST01        PM2.5  µg/m3
1     SN101       ST01          CO2    ppm
2     SN102       ST02        PM2.5  µg/m3
3     SN103       ST03        PM2.5  µg/m3
4     SN104       ST03  temperature     °C
5     SN105       ST04         PM10  µg/m3
6     SN106       ST05     humidity      %
7     SN107       ST06        PM2.5  µg/m3

In [37]:
len(df_sensors_silver)

8

In [38]:
set(df_sensors_silver["metric"].unique()) - set(UNIT_MAP)

set()

In [39]:
write_parquet(df_sensors_silver, "silver", "sensors")

print(f"sensors: {df_sensors_silver.equals(read_lake_parquet('silver', 'sensors'))}")

sensors: True

In [40]:
for b in lake.list_blobs(name_starts_with=STUDENT):
    print(b.name, b.size, b.last_modified)

shudria_oleh/bronze/readings/readings.parquet 4963 2026-07-27 20:06:44+00:00
shudria_oleh/bronze/sensors/sensors.parquet 4073 2026-07-27 20:06:44+00:00
shudria_oleh/bronze/stations/stations.parquet 4760 2026-07-27 20:06:44+00:00
shudria_oleh/gold/avg_by_city_metric/avg_by_city_metric.parquet 2956 2026-07-27 20:02:50+00:00
shudria_oleh/gold/daily_trend/daily_trend.parquet 2529 2026-07-27 20:02:50+00:00
shudria_oleh/gold/pm25_exceedances/pm25_exceedances.parquet 2903 2026-07-27 20:02:50+00:00
shudria_oleh/silver/_quality_report.json 1550 2026-07-27 20:02:50+00:00
shudria_oleh/silver/_tier_probe.json 208 2026-07-27 19:59:59+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=01/part.parquet 4535 2026-07-27 20:02:49+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=02/part.parquet 4474 2026-07-27 20:02:49+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=03/part.parquet 4486 2026-07-27 20:02:49+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=04/part.parquet 4524 2026-07-27 20:02:50+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=05/part.parquet 4425 2026-07-27 20:02:50+00:00
shudria_oleh/silver/sensors/sensors.parquet 2773 2026-07-27 20:06:45+00:00
shudria_oleh/silver/stations/stations.parquet 3441 2026-07-27 20:06:44+00:00
shudria_oleh/stations/stations.parquet 4724 2026-07-26 14:22:36+00:00

## 2.3. Таблиця readings

Найскладніша таблиця: десять операцій у визначеному порядку.

Порядок не довільний. Нормалізація `status` іде перед фільтром за статусом, інакше рядки з `OK` відсіялися б як некоректні. Відсів осиротілих `sensor_id` іде перед `merge` із `sensors`, інакше в приєднанні з'явилися б порожні метрики. Парсинг `measured_at` іде перед похідним `measured_date` і перед фільтром за датою.

`is_outlier` вимагає знати метрику виміру, а вона лежить у `sensors`, тому робиться тимчасовий `merge`; колонка `metric` у схему виходу не потрапляє.

Очікуваний результат порахований вручну до запуску: з 23 рядків мали лишитися 18. Відсіяно `R0005` (повний дублікат), `R0007` і `R0010` (статус `error` / `calibrating`, вони ж мають від'ємне й порожнє значення), `R0014` (сенсор `SN999` відсутній у `sensors`), `R0016` (немає дати).

Таблиця партиціонується за `measured_date`: 5 днів, ключ закодований у шляху `year=/month=/day=`.

In [41]:
df_readings_silver = read_lake_parquet("bronze", "readings")
df_readings_silver

,reading_id,sensor_id,value,measured_at,status,_ingested_at,_source_file
0,R0001,SN100,23.4,2026-07-01 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
1,R0002,SN100,"31,7",2026-07-01 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json
2,R0003,SN101,610,01/07/2026 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
3,R0004,SN102,18.9,2026.07.01 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
4,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
5,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
6,R0006,SN104,27.5,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
7,R0007,SN100,-3,2026-07-02 08:00,error,2026-07-27 20:06:43.256724+00:00,readings.json
8,R0008,SN105,52.0,2026-07-02 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
9,R0009,SN106,64,02/07/2026 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
10,R0010,SN101,NaN,2026-07-02 12:00,calibrating,2026-07-27 20:06:43.256724+00:00,readings.json
11,R0011,SN102,22.1,2026-07-02 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json
12,R0012,SN100,5000,2026-07-03 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
13,R0013,SN103,38.6,2026-07-03 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
14,R0014,SN999,40.0,2026-07-03 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
15,R0015,SN105,"49,8",2026-07-03 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
16,R0016,SN104,29.1,NaN,ok,2026-07-27 20:06:43.256724+00:00,readings.json
17,R0017,SN100,26.3,2026-07-04 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
18,R0018,SN106,71,2026-07-04 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
19,R0019,SN102,20.4,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
20,R0020,SN101,720,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
21,R0021,SN103,41.0,04/07/2026 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
22,R0022,SN105,55.7,2026-07-05 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json

In [42]:
df_sensors_silver_ref = read_lake_parquet("silver", "sensors")
sensor_ids = set(df_sensors_silver_ref["sensor_id"])
sensor_ids

{'SN100', 'SN101', 'SN102', 'SN103', 'SN104', 'SN105', 'SN106', 'SN107'}

In [43]:
filter_sensors = df_readings_silver["sensor_id"].isin(sensor_ids)

_before = len(df_readings_silver)
df_readings_silver = df_readings_silver[filter_sensors].reset_index(drop=True)
log_drop("readings", "sensor_id відсутній у Silver-таблиці sensors", _before, len(df_readings_silver))

df_readings_silver

,reading_id,sensor_id,value,measured_at,status,_ingested_at,_source_file
0,R0001,SN100,23.4,2026-07-01 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
1,R0002,SN100,"31,7",2026-07-01 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json
2,R0003,SN101,610,01/07/2026 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
3,R0004,SN102,18.9,2026.07.01 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
4,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
5,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
6,R0006,SN104,27.5,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
7,R0007,SN100,-3,2026-07-02 08:00,error,2026-07-27 20:06:43.256724+00:00,readings.json
8,R0008,SN105,52.0,2026-07-02 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
9,R0009,SN106,64,02/07/2026 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
10,R0010,SN101,NaN,2026-07-02 12:00,calibrating,2026-07-27 20:06:43.256724+00:00,readings.json
11,R0011,SN102,22.1,2026-07-02 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json
12,R0012,SN100,5000,2026-07-03 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
13,R0013,SN103,38.6,2026-07-03 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
14,R0015,SN105,"49,8",2026-07-03 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
15,R0016,SN104,29.1,NaN,ok,2026-07-27 20:06:43.256724+00:00,readings.json
16,R0017,SN100,26.3,2026-07-04 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
17,R0018,SN106,71,2026-07-04 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
18,R0019,SN102,20.4,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
19,R0020,SN101,720,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
20,R0021,SN103,41.0,04/07/2026 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json
21,R0022,SN105,55.7,2026-07-05 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json

In [44]:
df_readings_silver["status_normalized"] = df_readings_silver["status"].str.lower()
df_readings_silver

,reading_id,sensor_id,value,measured_at,status,_ingested_at,_source_file,status_normalized
0,R0001,SN100,23.4,2026-07-01 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
1,R0002,SN100,"31,7",2026-07-01 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json,ok
2,R0003,SN101,610,01/07/2026 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
3,R0004,SN102,18.9,2026.07.01 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
4,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
5,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
6,R0006,SN104,27.5,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
7,R0007,SN100,-3,2026-07-02 08:00,error,2026-07-27 20:06:43.256724+00:00,readings.json,error
8,R0008,SN105,52.0,2026-07-02 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
9,R0009,SN106,64,02/07/2026 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
10,R0010,SN101,NaN,2026-07-02 12:00,calibrating,2026-07-27 20:06:43.256724+00:00,readings.json,calibrating
11,R0011,SN102,22.1,2026-07-02 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json,ok
12,R0012,SN100,5000,2026-07-03 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
13,R0013,SN103,38.6,2026-07-03 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
14,R0015,SN105,"49,8",2026-07-03 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
15,R0016,SN104,29.1,NaN,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
16,R0017,SN100,26.3,2026-07-04 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
17,R0018,SN106,71,2026-07-04 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
18,R0019,SN102,20.4,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
19,R0020,SN101,720,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
20,R0021,SN103,41.0,04/07/2026 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
21,R0022,SN105,55.7,2026-07-05 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok

In [45]:
_before = len(df_readings_silver)
df_readings_silver = df_readings_silver[df_readings_silver["status_normalized"] == "ok"].reset_index(drop=True)
log_drop("readings", "status не дорівнює ok (error або calibrating)", _before, len(df_readings_silver))

df_readings_silver

,reading_id,sensor_id,value,measured_at,status,_ingested_at,_source_file,status_normalized
0,R0001,SN100,23.4,2026-07-01 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
1,R0002,SN100,"31,7",2026-07-01 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json,ok
2,R0003,SN101,610,01/07/2026 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
3,R0004,SN102,18.9,2026.07.01 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
4,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
5,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
6,R0006,SN104,27.5,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
7,R0008,SN105,52.0,2026-07-02 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
8,R0009,SN106,64,02/07/2026 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
9,R0011,SN102,22.1,2026-07-02 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json,ok
10,R0012,SN100,5000,2026-07-03 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
11,R0013,SN103,38.6,2026-07-03 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
12,R0015,SN105,"49,8",2026-07-03 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
13,R0016,SN104,29.1,NaN,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
14,R0017,SN100,26.3,2026-07-04 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
15,R0018,SN106,71,2026-07-04 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
16,R0019,SN102,20.4,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
17,R0020,SN101,720,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
18,R0021,SN103,41.0,04/07/2026 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok
19,R0022,SN105,55.7,2026-07-05 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok

In [46]:
df_readings_silver["value_normalized"] = pd.to_numeric(df_readings_silver["value"].str.replace(",", "."), errors="coerce")
df_readings_silver

,reading_id,sensor_id,value,measured_at,status,_ingested_at,_source_file,status_normalized,value_normalized
0,R0001,SN100,23.4,2026-07-01 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,23.4
1,R0002,SN100,"31,7",2026-07-01 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json,ok,31.7
2,R0003,SN101,610,01/07/2026 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,610.0
3,R0004,SN102,18.9,2026.07.01 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,18.9
4,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,45.2
5,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,45.2
6,R0006,SN104,27.5,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,27.5
7,R0008,SN105,52.0,2026-07-02 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,52.0
8,R0009,SN106,64,02/07/2026 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,64.0
9,R0011,SN102,22.1,2026-07-02 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json,ok,22.1
10,R0012,SN100,5000,2026-07-03 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,5000.0
11,R0013,SN103,38.6,2026-07-03 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,38.6
12,R0015,SN105,"49,8",2026-07-03 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,49.8
13,R0016,SN104,29.1,NaN,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,29.1
14,R0017,SN100,26.3,2026-07-04 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,26.3
15,R0018,SN106,71,2026-07-04 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,71.0
16,R0019,SN102,20.4,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,20.4
17,R0020,SN101,720,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,720.0
18,R0021,SN103,41.0,04/07/2026 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,41.0
19,R0022,SN105,55.7,2026-07-05 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,55.7

In [47]:
# умова >= 0 відсіює і від'ємні значення, і пропуски: NaN не проходить жодного порівняння
_before = len(df_readings_silver)
df_readings_silver = df_readings_silver[df_readings_silver["value_normalized"] >= 0].reset_index(drop=True)
log_drop("readings", "value порожнє або від'ємне", _before, len(df_readings_silver))

df_readings_silver

,reading_id,sensor_id,value,measured_at,status,_ingested_at,_source_file,status_normalized,value_normalized
0,R0001,SN100,23.4,2026-07-01 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,23.4
1,R0002,SN100,"31,7",2026-07-01 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json,ok,31.7
2,R0003,SN101,610,01/07/2026 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,610.0
3,R0004,SN102,18.9,2026.07.01 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,18.9
4,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,45.2
5,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,45.2
6,R0006,SN104,27.5,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,27.5
7,R0008,SN105,52.0,2026-07-02 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,52.0
8,R0009,SN106,64,02/07/2026 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,64.0
9,R0011,SN102,22.1,2026-07-02 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json,ok,22.1
10,R0012,SN100,5000,2026-07-03 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,5000.0
11,R0013,SN103,38.6,2026-07-03 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,38.6
12,R0015,SN105,"49,8",2026-07-03 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,49.8
13,R0016,SN104,29.1,NaN,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,29.1
14,R0017,SN100,26.3,2026-07-04 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,26.3
15,R0018,SN106,71,2026-07-04 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,71.0
16,R0019,SN102,20.4,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,20.4
17,R0020,SN101,720,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,720.0
18,R0021,SN103,41.0,04/07/2026 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,41.0
19,R0022,SN105,55.7,2026-07-05 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,55.7

In [48]:
df_readings_silver["measured_at_normalized1"] = pd.to_datetime(
    df_readings_silver["measured_at"].str.replace(r"[/.]", "-", regex=True),
    format="%Y-%m-%d %H:%M",
    errors="coerce"
)

df_readings_silver["measured_at_normalized2"] = pd.to_datetime(
    df_readings_silver["measured_at"].str.replace(r"[/.]", "-", regex=True),
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)
df_readings_silver

,reading_id,sensor_id,value,measured_at,status,_ingested_at,_source_file,status_normalized,value_normalized,measured_at_normalized1,measured_at_normalized2
0,R0001,SN100,23.4,2026-07-01 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,23.4,2026-07-01 08:00:00,NaT
1,R0002,SN100,"31,7",2026-07-01 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json,ok,31.7,2026-07-01 12:00:00,NaT
2,R0003,SN101,610,01/07/2026 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,610.0,NaT,2026-07-01 08:00:00
3,R0004,SN102,18.9,2026.07.01 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,18.9,2026-07-01 09:00:00,NaT
4,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,45.2,2026-07-01 10:00:00,NaT
5,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,45.2,2026-07-01 10:00:00,NaT
6,R0006,SN104,27.5,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,27.5,2026-07-01 10:00:00,NaT
7,R0008,SN105,52.0,2026-07-02 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,52.0,2026-07-02 09:00:00,NaT
8,R0009,SN106,64,02/07/2026 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,64.0,NaT,2026-07-02 09:00:00
9,R0011,SN102,22.1,2026-07-02 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json,ok,22.1,2026-07-02 12:00:00,NaT
10,R0012,SN100,5000,2026-07-03 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,5000.0,2026-07-03 08:00:00,NaT
11,R0013,SN103,38.6,2026-07-03 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,38.6,2026-07-03 10:00:00,NaT
12,R0015,SN105,"49,8",2026-07-03 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,49.8,2026-07-03 11:00:00,NaT
13,R0016,SN104,29.1,NaN,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,29.1,NaT,NaT
14,R0017,SN100,26.3,2026-07-04 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,26.3,2026-07-04 08:00:00,NaT
15,R0018,SN106,71,2026-07-04 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,71.0,2026-07-04 09:00:00,NaT
16,R0019,SN102,20.4,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,20.4,2026-07-04 12:00:00,NaT
17,R0020,SN101,720,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,720.0,2026-07-04 12:00:00,NaT
18,R0021,SN103,41.0,04/07/2026 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,41.0,NaT,2026-07-04 10:00:00
19,R0022,SN105,55.7,2026-07-05 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,55.7,2026-07-05 11:00:00,NaT

In [49]:
df_readings_silver["measured_at_normalized"] = df_readings_silver["measured_at_normalized1"].fillna(df_readings_silver["measured_at_normalized2"])

df_readings_silver

,reading_id,sensor_id,value,measured_at,status,_ingested_at,_source_file,status_normalized,value_normalized,measured_at_normalized1,measured_at_normalized2,measured_at_normalized
0,R0001,SN100,23.4,2026-07-01 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,23.4,2026-07-01 08:00:00,NaT,2026-07-01 08:00:00
1,R0002,SN100,"31,7",2026-07-01 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json,ok,31.7,2026-07-01 12:00:00,NaT,2026-07-01 12:00:00
2,R0003,SN101,610,01/07/2026 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,610.0,NaT,2026-07-01 08:00:00,2026-07-01 08:00:00
3,R0004,SN102,18.9,2026.07.01 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,18.9,2026-07-01 09:00:00,NaT,2026-07-01 09:00:00
4,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,45.2,2026-07-01 10:00:00,NaT,2026-07-01 10:00:00
5,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,45.2,2026-07-01 10:00:00,NaT,2026-07-01 10:00:00
6,R0006,SN104,27.5,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,27.5,2026-07-01 10:00:00,NaT,2026-07-01 10:00:00
7,R0008,SN105,52.0,2026-07-02 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,52.0,2026-07-02 09:00:00,NaT,2026-07-02 09:00:00
8,R0009,SN106,64,02/07/2026 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,64.0,NaT,2026-07-02 09:00:00,2026-07-02 09:00:00
9,R0011,SN102,22.1,2026-07-02 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json,ok,22.1,2026-07-02 12:00:00,NaT,2026-07-02 12:00:00
10,R0012,SN100,5000,2026-07-03 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,5000.0,2026-07-03 08:00:00,NaT,2026-07-03 08:00:00
11,R0013,SN103,38.6,2026-07-03 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,38.6,2026-07-03 10:00:00,NaT,2026-07-03 10:00:00
12,R0015,SN105,"49,8",2026-07-03 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,49.8,2026-07-03 11:00:00,NaT,2026-07-03 11:00:00
13,R0016,SN104,29.1,NaN,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,29.1,NaT,NaT,NaT
14,R0017,SN100,26.3,2026-07-04 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,26.3,2026-07-04 08:00:00,NaT,2026-07-04 08:00:00
15,R0018,SN106,71,2026-07-04 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,71.0,2026-07-04 09:00:00,NaT,2026-07-04 09:00:00
16,R0019,SN102,20.4,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,20.4,2026-07-04 12:00:00,NaT,2026-07-04 12:00:00
17,R0020,SN101,720,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,720.0,2026-07-04 12:00:00,NaT,2026-07-04 12:00:00
18,R0021,SN103,41.0,04/07/2026 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,41.0,NaT,2026-07-04 10:00:00,2026-07-04 10:00:00
19,R0022,SN105,55.7,2026-07-05 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,55.7,2026-07-05 11:00:00,NaT,2026-07-05 11:00:00

In [50]:
_before = len(df_readings_silver)
df_readings_silver = df_readings_silver[df_readings_silver["measured_at_normalized"].notna()].reset_index(drop=True)
log_drop("readings", "measured_at не розпізнано як дату", _before, len(df_readings_silver))

df_readings_silver

,reading_id,sensor_id,value,measured_at,status,_ingested_at,_source_file,status_normalized,value_normalized,measured_at_normalized1,measured_at_normalized2,measured_at_normalized
0,R0001,SN100,23.4,2026-07-01 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,23.4,2026-07-01 08:00:00,NaT,2026-07-01 08:00:00
1,R0002,SN100,"31,7",2026-07-01 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json,ok,31.7,2026-07-01 12:00:00,NaT,2026-07-01 12:00:00
2,R0003,SN101,610,01/07/2026 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,610.0,NaT,2026-07-01 08:00:00,2026-07-01 08:00:00
3,R0004,SN102,18.9,2026.07.01 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,18.9,2026-07-01 09:00:00,NaT,2026-07-01 09:00:00
4,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,45.2,2026-07-01 10:00:00,NaT,2026-07-01 10:00:00
5,R0005,SN103,45.2,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,45.2,2026-07-01 10:00:00,NaT,2026-07-01 10:00:00
6,R0006,SN104,27.5,2026-07-01 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,27.5,2026-07-01 10:00:00,NaT,2026-07-01 10:00:00
7,R0008,SN105,52.0,2026-07-02 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,52.0,2026-07-02 09:00:00,NaT,2026-07-02 09:00:00
8,R0009,SN106,64,02/07/2026 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,64.0,NaT,2026-07-02 09:00:00,2026-07-02 09:00:00
9,R0011,SN102,22.1,2026-07-02 12:00,OK,2026-07-27 20:06:43.256724+00:00,readings.json,ok,22.1,2026-07-02 12:00:00,NaT,2026-07-02 12:00:00
10,R0012,SN100,5000,2026-07-03 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,5000.0,2026-07-03 08:00:00,NaT,2026-07-03 08:00:00
11,R0013,SN103,38.6,2026-07-03 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,38.6,2026-07-03 10:00:00,NaT,2026-07-03 10:00:00
12,R0015,SN105,"49,8",2026-07-03 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,49.8,2026-07-03 11:00:00,NaT,2026-07-03 11:00:00
13,R0017,SN100,26.3,2026-07-04 08:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,26.3,2026-07-04 08:00:00,NaT,2026-07-04 08:00:00
14,R0018,SN106,71,2026-07-04 09:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,71.0,2026-07-04 09:00:00,NaT,2026-07-04 09:00:00
15,R0019,SN102,20.4,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,20.4,2026-07-04 12:00:00,NaT,2026-07-04 12:00:00
16,R0020,SN101,720,2026-07-04 12:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,720.0,2026-07-04 12:00:00,NaT,2026-07-04 12:00:00
17,R0021,SN103,41.0,04/07/2026 10:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,41.0,NaT,2026-07-04 10:00:00,2026-07-04 10:00:00
18,R0022,SN105,55.7,2026-07-05 11:00,ok,2026-07-27 20:06:43.256724+00:00,readings.json,ok,55.7,2026-07-05 11:00:00,NaT,2026-07-05 11:00:00

In [51]:
df_readings_silver = df_readings_silver[["reading_id", "sensor_id", "value_normalized", "measured_at_normalized", "status_normalized"]]
df_readings_silver

,reading_id,sensor_id,value_normalized,measured_at_normalized,status_normalized
0,R0001,SN100,23.4,2026-07-01 08:00:00,ok
1,R0002,SN100,31.7,2026-07-01 12:00:00,ok
2,R0003,SN101,610.0,2026-07-01 08:00:00,ok
3,R0004,SN102,18.9,2026-07-01 09:00:00,ok
4,R0005,SN103,45.2,2026-07-01 10:00:00,ok
5,R0005,SN103,45.2,2026-07-01 10:00:00,ok
6,R0006,SN104,27.5,2026-07-01 10:00:00,ok
7,R0008,SN105,52.0,2026-07-02 09:00:00,ok
8,R0009,SN106,64.0,2026-07-02 09:00:00,ok
9,R0011,SN102,22.1,2026-07-02 12:00:00,ok
10,R0012,SN100,5000.0,2026-07-03 08:00:00,ok
11,R0013,SN103,38.6,2026-07-03 10:00:00,ok
12,R0015,SN105,49.8,2026-07-03 11:00:00,ok
13,R0017,SN100,26.3,2026-07-04 08:00:00,ok
14,R0018,SN106,71.0,2026-07-04 09:00:00,ok
15,R0019,SN102,20.4,2026-07-04 12:00:00,ok
16,R0020,SN101,720.0,2026-07-04 12:00:00,ok
17,R0021,SN103,41.0,2026-07-04 10:00:00,ok
18,R0022,SN105,55.7,2026-07-05 11:00:00,ok

In [52]:
_before = len(df_readings_silver)
df_readings_silver = df_readings_silver.drop_duplicates().reset_index(drop=True)
log_drop("readings", "повні дублікати рядків", _before, len(df_readings_silver))

df_readings_silver

,reading_id,sensor_id,value_normalized,measured_at_normalized,status_normalized
0,R0001,SN100,23.4,2026-07-01 08:00:00,ok
1,R0002,SN100,31.7,2026-07-01 12:00:00,ok
2,R0003,SN101,610.0,2026-07-01 08:00:00,ok
3,R0004,SN102,18.9,2026-07-01 09:00:00,ok
4,R0005,SN103,45.2,2026-07-01 10:00:00,ok
5,R0006,SN104,27.5,2026-07-01 10:00:00,ok
6,R0008,SN105,52.0,2026-07-02 09:00:00,ok
7,R0009,SN106,64.0,2026-07-02 09:00:00,ok
8,R0011,SN102,22.1,2026-07-02 12:00:00,ok
9,R0012,SN100,5000.0,2026-07-03 08:00:00,ok
10,R0013,SN103,38.6,2026-07-03 10:00:00,ok
11,R0015,SN105,49.8,2026-07-03 11:00:00,ok
12,R0017,SN100,26.3,2026-07-04 08:00:00,ok
13,R0018,SN106,71.0,2026-07-04 09:00:00,ok
14,R0019,SN102,20.4,2026-07-04 12:00:00,ok
15,R0020,SN101,720.0,2026-07-04 12:00:00,ok
16,R0021,SN103,41.0,2026-07-04 10:00:00,ok
17,R0022,SN105,55.7,2026-07-05 11:00:00,ok

In [53]:
df_readings_silver["measured_date"] = df_readings_silver["measured_at_normalized"].dt.normalize()
df_readings_silver

,reading_id,sensor_id,value_normalized,measured_at_normalized,status_normalized,measured_date
0,R0001,SN100,23.4,2026-07-01 08:00:00,ok,2026-07-01
1,R0002,SN100,31.7,2026-07-01 12:00:00,ok,2026-07-01
2,R0003,SN101,610.0,2026-07-01 08:00:00,ok,2026-07-01
3,R0004,SN102,18.9,2026-07-01 09:00:00,ok,2026-07-01
4,R0005,SN103,45.2,2026-07-01 10:00:00,ok,2026-07-01
5,R0006,SN104,27.5,2026-07-01 10:00:00,ok,2026-07-01
6,R0008,SN105,52.0,2026-07-02 09:00:00,ok,2026-07-02
7,R0009,SN106,64.0,2026-07-02 09:00:00,ok,2026-07-02
8,R0011,SN102,22.1,2026-07-02 12:00:00,ok,2026-07-02
9,R0012,SN100,5000.0,2026-07-03 08:00:00,ok,2026-07-03
10,R0013,SN103,38.6,2026-07-03 10:00:00,ok,2026-07-03
11,R0015,SN105,49.8,2026-07-03 11:00:00,ok,2026-07-03
12,R0017,SN100,26.3,2026-07-04 08:00:00,ok,2026-07-04
13,R0018,SN106,71.0,2026-07-04 09:00:00,ok,2026-07-04
14,R0019,SN102,20.4,2026-07-04 12:00:00,ok,2026-07-04
15,R0020,SN101,720.0,2026-07-04 12:00:00,ok,2026-07-04
16,R0021,SN103,41.0,2026-07-04 10:00:00,ok,2026-07-04
17,R0022,SN105,55.7,2026-07-05 11:00:00,ok,2026-07-05

In [54]:
len_readings_before = len(df_readings_silver)
df_readings_silver_merge = df_readings_silver.merge(
    df_sensors_silver[["sensor_id", "metric"]], on="sensor_id", how="left"
)

len_readings_after = len(df_readings_silver_merge)

print(f"len_readings_before: {len_readings_before}, len_readings_after: {len_readings_after}")

len_readings_before: 18, len_readings_after: 18

In [55]:
df_readings_silver_merge["is_outlier"] = ((df_readings_silver_merge["value_normalized"]> 500) &
                                                    (df_readings_silver_merge["metric"] == "PM2.5"))
df_readings_silver_merge

,reading_id,sensor_id,value_normalized,measured_at_normalized,status_normalized,measured_date,metric,is_outlier
0,R0001,SN100,23.4,2026-07-01 08:00:00,ok,2026-07-01,PM2.5,False
1,R0002,SN100,31.7,2026-07-01 12:00:00,ok,2026-07-01,PM2.5,False
2,R0003,SN101,610.0,2026-07-01 08:00:00,ok,2026-07-01,CO2,False
3,R0004,SN102,18.9,2026-07-01 09:00:00,ok,2026-07-01,PM2.5,False
4,R0005,SN103,45.2,2026-07-01 10:00:00,ok,2026-07-01,PM2.5,False
5,R0006,SN104,27.5,2026-07-01 10:00:00,ok,2026-07-01,temperature,False
6,R0008,SN105,52.0,2026-07-02 09:00:00,ok,2026-07-02,PM10,False
7,R0009,SN106,64.0,2026-07-02 09:00:00,ok,2026-07-02,humidity,False
8,R0011,SN102,22.1,2026-07-02 12:00:00,ok,2026-07-02,PM2.5,False
9,R0012,SN100,5000.0,2026-07-03 08:00:00,ok,2026-07-03,PM2.5,True
10,R0013,SN103,38.6,2026-07-03 10:00:00,ok,2026-07-03,PM2.5,False
11,R0015,SN105,49.8,2026-07-03 11:00:00,ok,2026-07-03,PM10,False
12,R0017,SN100,26.3,2026-07-04 08:00:00,ok,2026-07-04,PM2.5,False
13,R0018,SN106,71.0,2026-07-04 09:00:00,ok,2026-07-04,humidity,False
14,R0019,SN102,20.4,2026-07-04 12:00:00,ok,2026-07-04,PM2.5,False
15,R0020,SN101,720.0,2026-07-04 12:00:00,ok,2026-07-04,CO2,False
16,R0021,SN103,41.0,2026-07-04 10:00:00,ok,2026-07-04,PM2.5,False
17,R0022,SN105,55.7,2026-07-05 11:00:00,ok,2026-07-05,PM10,False

In [56]:
df_readings_silver_merge = df_readings_silver_merge[["reading_id", "sensor_id", "value_normalized", "measured_at_normalized", "measured_date", "status_normalized", "is_outlier"]]
df_readings_silver_merge =  df_readings_silver_merge.rename(
    columns={
        "value_normalized": "value",
        "measured_at_normalized": "measured_at",
        "status_normalized": "status"
    })
df_readings_silver_merge

,reading_id,sensor_id,value,measured_at,measured_date,status,is_outlier
0,R0001,SN100,23.4,2026-07-01 08:00:00,2026-07-01,ok,False
1,R0002,SN100,31.7,2026-07-01 12:00:00,2026-07-01,ok,False
2,R0003,SN101,610.0,2026-07-01 08:00:00,2026-07-01,ok,False
3,R0004,SN102,18.9,2026-07-01 09:00:00,2026-07-01,ok,False
4,R0005,SN103,45.2,2026-07-01 10:00:00,2026-07-01,ok,False
5,R0006,SN104,27.5,2026-07-01 10:00:00,2026-07-01,ok,False
6,R0008,SN105,52.0,2026-07-02 09:00:00,2026-07-02,ok,False
7,R0009,SN106,64.0,2026-07-02 09:00:00,2026-07-02,ok,False
8,R0011,SN102,22.1,2026-07-02 12:00:00,2026-07-02,ok,False
9,R0012,SN100,5000.0,2026-07-03 08:00:00,2026-07-03,ok,True
10,R0013,SN103,38.6,2026-07-03 10:00:00,2026-07-03,ok,False
11,R0015,SN105,49.8,2026-07-03 11:00:00,2026-07-03,ok,False
12,R0017,SN100,26.3,2026-07-04 08:00:00,2026-07-04,ok,False
13,R0018,SN106,71.0,2026-07-04 09:00:00,2026-07-04,ok,False
14,R0019,SN102,20.4,2026-07-04 12:00:00,2026-07-04,ok,False
15,R0020,SN101,720.0,2026-07-04 12:00:00,2026-07-04,ok,False
16,R0021,SN103,41.0,2026-07-04 10:00:00,2026-07-04,ok,False
17,R0022,SN105,55.7,2026-07-05 11:00:00,2026-07-05,ok,False

In [57]:
df_readings_silver_merge["measured_date"].value_counts()

measured_date
2026-07-01    6
2026-07-04    5
2026-07-02    3
2026-07-03    3
2026-07-05    1
Name: count, dtype: int64

In [58]:

for date, group in df_readings_silver_merge.groupby("measured_date"):
    print(f"{STUDENT}/silver/readings/year={date.year}/month={date.month:02d}/day={date.day:02d}/part.parquet")

shudria_oleh/silver/readings/year=2026/month=07/day=01/part.parquet
shudria_oleh/silver/readings/year=2026/month=07/day=02/part.parquet
shudria_oleh/silver/readings/year=2026/month=07/day=03/part.parquet
shudria_oleh/silver/readings/year=2026/month=07/day=04/part.parquet
shudria_oleh/silver/readings/year=2026/month=07/day=05/part.parquet

In [59]:
def write_parquet_silver_partitioned(df):
    for date, group in df.groupby("measured_date"):
        buf = BytesIO()
        group.to_parquet(buf, index=False)
        buf.seek(0)

        lake.upload_blob(
            name=(f"{STUDENT}/silver/readings/year={date.year}/month={date.month:02d}/day={date.day:02d}/part.parquet"),
            data=buf.getvalue(),
            overwrite=True
        )

In [60]:
write_parquet_silver_partitioned(df_readings_silver_merge)

In [61]:
for b in lake.list_blobs(name_starts_with=STUDENT):
    print(b.name, b.size, b.last_modified)

shudria_oleh/bronze/readings/readings.parquet 4963 2026-07-27 20:06:44+00:00
shudria_oleh/bronze/sensors/sensors.parquet 4073 2026-07-27 20:06:44+00:00
shudria_oleh/bronze/stations/stations.parquet 4760 2026-07-27 20:06:44+00:00
shudria_oleh/gold/avg_by_city_metric/avg_by_city_metric.parquet 2956 2026-07-27 20:02:50+00:00
shudria_oleh/gold/daily_trend/daily_trend.parquet 2529 2026-07-27 20:02:50+00:00
shudria_oleh/gold/pm25_exceedances/pm25_exceedances.parquet 2903 2026-07-27 20:02:50+00:00
shudria_oleh/silver/_quality_report.json 1550 2026-07-27 20:02:50+00:00
shudria_oleh/silver/_tier_probe.json 208 2026-07-27 19:59:59+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=01/part.parquet 4535 2026-07-27 20:06:45+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=02/part.parquet 4474 2026-07-27 20:06:45+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=03/part.parquet 4486 2026-07-27 20:06:45+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=04/part.parquet 4524 2026-07-27 20:06:45+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=05/part.parquet 4425 2026-07-27 20:06:46+00:00
shudria_oleh/silver/sensors/sensors.parquet 2773 2026-07-27 20:06:45+00:00
shudria_oleh/silver/stations/stations.parquet 3441 2026-07-27 20:06:44+00:00
shudria_oleh/stations/stations.parquet 4724 2026-07-26 14:22:36+00:00

In [62]:
pd.read_parquet(BytesIO(lake.download_blob("shudria_oleh/silver/readings/year=2026/month=07/day=01/part.parquet").readall()))

,reading_id,sensor_id,value,measured_at,measured_date,status,is_outlier
0,R0001,SN100,23.4,2026-07-01 08:00:00,2026-07-01,ok,False
1,R0002,SN100,31.7,2026-07-01 12:00:00,2026-07-01,ok,False
2,R0003,SN101,610.0,2026-07-01 08:00:00,2026-07-01,ok,False
3,R0004,SN102,18.9,2026-07-01 09:00:00,2026-07-01,ok,False
4,R0005,SN103,45.2,2026-07-01 10:00:00,2026-07-01,ok,False
5,R0006,SN104,27.5,2026-07-01 10:00:00,2026-07-01,ok,False

# Крок 3. Gold

Готові вітрини для аналітики: агрегати поверх Silver, побудовані через `merge` і `groupby`.

Виміри з `is_outlier = True` в агрегати не включаються.

## 3.1. Середні показники по містах

Об'єднання `readings` + `sensors` + `stations`, групування за `city` і `metric`.

Вихід: `city`, `metric`, `avg_value`, `readings_count`.

In [63]:
def read_lake_parquet_silver_readings_partitioned():
    blobs = lake.list_blobs(name_starts_with=f"{STUDENT}/silver/readings/")
    df = pd.DataFrame()
    for blob in blobs:
        blob = lake.download_blob(blob.name).readall()
        df = pd.concat([df, pd.read_parquet(BytesIO(blob), engine="pyarrow")]).reset_index(drop=True)
    return df

In [64]:
df_readings_silver_lake = read_lake_parquet_silver_readings_partitioned()
df_readings_silver_lake = df_readings_silver_lake[df_readings_silver_lake["is_outlier"] == False].reset_index(drop=True)
df_readings_silver_lake

,reading_id,sensor_id,value,measured_at,measured_date,status,is_outlier
0,R0001,SN100,23.4,2026-07-01 08:00:00,2026-07-01,ok,False
1,R0002,SN100,31.7,2026-07-01 12:00:00,2026-07-01,ok,False
2,R0003,SN101,610.0,2026-07-01 08:00:00,2026-07-01,ok,False
3,R0004,SN102,18.9,2026-07-01 09:00:00,2026-07-01,ok,False
4,R0005,SN103,45.2,2026-07-01 10:00:00,2026-07-01,ok,False
5,R0006,SN104,27.5,2026-07-01 10:00:00,2026-07-01,ok,False
6,R0008,SN105,52.0,2026-07-02 09:00:00,2026-07-02,ok,False
7,R0009,SN106,64.0,2026-07-02 09:00:00,2026-07-02,ok,False
8,R0011,SN102,22.1,2026-07-02 12:00:00,2026-07-02,ok,False
9,R0013,SN103,38.6,2026-07-03 10:00:00,2026-07-03,ok,False
10,R0015,SN105,49.8,2026-07-03 11:00:00,2026-07-03,ok,False
11,R0017,SN100,26.3,2026-07-04 08:00:00,2026-07-04,ok,False
12,R0018,SN106,71.0,2026-07-04 09:00:00,2026-07-04,ok,False
13,R0019,SN102,20.4,2026-07-04 12:00:00,2026-07-04,ok,False
14,R0020,SN101,720.0,2026-07-04 12:00:00,2026-07-04,ok,False
15,R0021,SN103,41.0,2026-07-04 10:00:00,2026-07-04,ok,False
16,R0022,SN105,55.7,2026-07-05 11:00:00,2026-07-05,ok,False

In [65]:
len_table_before = len(df_readings_silver_lake)
df_merge = df_readings_silver_lake.merge(
    df_sensors_silver[["station_id", "metric", "sensor_id"]], on="sensor_id"
).merge(
    df_stations_silver[["city", "country", "name", "station_id"]], on="station_id"
)

len_table_after = len(df_merge)
print(f"len_table_before: {len_table_before}, len_table_after: {len_table_after}")
df_merge

len_table_before: 17, len_table_after: 17

,reading_id,sensor_id,value,measured_at,measured_date,status,is_outlier,station_id,metric,city,country,name
0,R0001,SN100,23.4,2026-07-01 08:00:00,2026-07-01,ok,False,ST01,PM2.5,Kyiv,UA,Центр
1,R0002,SN100,31.7,2026-07-01 12:00:00,2026-07-01,ok,False,ST01,PM2.5,Kyiv,UA,Центр
2,R0003,SN101,610.0,2026-07-01 08:00:00,2026-07-01,ok,False,ST01,CO2,Kyiv,UA,Центр
3,R0004,SN102,18.9,2026-07-01 09:00:00,2026-07-01,ok,False,ST02,PM2.5,Kyiv,UA,Оболонь
4,R0005,SN103,45.2,2026-07-01 10:00:00,2026-07-01,ok,False,ST03,PM2.5,Lviv,UA,Личаків
5,R0006,SN104,27.5,2026-07-01 10:00:00,2026-07-01,ok,False,ST03,temperature,Lviv,UA,Личаків
6,R0008,SN105,52.0,2026-07-02 09:00:00,2026-07-02,ok,False,ST04,PM10,Kraków,PL,Stare Miasto
7,R0009,SN106,64.0,2026-07-02 09:00:00,2026-07-02,ok,False,ST05,humidity,Warsaw,PL,Centrum
8,R0011,SN102,22.1,2026-07-02 12:00:00,2026-07-02,ok,False,ST02,PM2.5,Kyiv,UA,Оболонь
9,R0013,SN103,38.6,2026-07-03 10:00:00,2026-07-03,ok,False,ST03,PM2.5,Lviv,UA,Личаків
10,R0015,SN105,49.8,2026-07-03 11:00:00,2026-07-03,ok,False,ST04,PM10,Kraków,PL,Stare Miasto
11,R0017,SN100,26.3,2026-07-04 08:00:00,2026-07-04,ok,False,ST01,PM2.5,Kyiv,UA,Центр
12,R0018,SN106,71.0,2026-07-04 09:00:00,2026-07-04,ok,False,ST05,humidity,Warsaw,PL,Centrum
13,R0019,SN102,20.4,2026-07-04 12:00:00,2026-07-04,ok,False,ST02,PM2.5,Kyiv,UA,Оболонь
14,R0020,SN101,720.0,2026-07-04 12:00:00,2026-07-04,ok,False,ST01,CO2,Kyiv,UA,Центр
15,R0021,SN103,41.0,2026-07-04 10:00:00,2026-07-04,ok,False,ST03,PM2.5,Lviv,UA,Личаків
16,R0022,SN105,55.7,2026-07-05 11:00:00,2026-07-05,ok,False,ST04,PM10,Kraków,PL,Stare Miasto

In [66]:
avg_by_city_metric = df_merge.groupby(["city", "metric"], as_index=False).agg(
    avg_value=("value", "mean"),
    readings_count=("reading_id", "count")
)
avg_by_city_metric

     city       metric  avg_value  readings_count
0  Kraków         PM10       52.5               3
1    Kyiv          CO2      665.0               2
2    Kyiv        PM2.5       23.8               6
3    Lviv        PM2.5       41.6               3
4    Lviv  temperature       27.5               1
5  Warsaw     humidity       67.5               2

## 3.2. Перевищення норми PM2.5

Лише записи з `metric = PM2.5`. Рахуємо кількість вимірів, де `value > 25`, у розрізі станції. Поріг 25 заданий умовно.

Вихід: `station_id`, `station_name`, `city`, `exceedances_count`.

In [67]:
pm25_exceedances = df_merge[(df_merge["metric"] == "PM2.5") & (df_merge["value"] > 25)].groupby(["station_id", "name", "city"], as_index=False).agg(
    exceedances_count=("reading_id", "count")
)
pm25_exceedances = pm25_exceedances.rename(columns={"name": "station_name"})
pm25_exceedances

  station_id station_name  city  exceedances_count
0       ST01        Центр  Kyiv                  2
1       ST03      Личаків  Lviv                  3

Станції без жодного перевищення у вітрину не потрапляють. Завдання не уточнює поведінку для нульових значень; обрано варіант, за якого вітрина містить лише факти перевищень.

## 3.3. Добова динаміка

Групування за `measured_date` і `metric`.

Вихід: `measured_date`, `metric`, `avg_value`.

In [68]:
daily_trend = df_merge.groupby(["measured_date", "metric"], as_index=False).agg(
    avg_value=("value", "mean")
)
daily_trend

   measured_date       metric   avg_value
0     2026-07-01          CO2  610.000000
1     2026-07-01        PM2.5   29.800000
2     2026-07-01  temperature   27.500000
3     2026-07-02         PM10   52.000000
4     2026-07-02        PM2.5   22.100000
5     2026-07-02     humidity   64.000000
6     2026-07-03         PM10   49.800000
7     2026-07-03        PM2.5   38.600000
8     2026-07-04          CO2  720.000000
9     2026-07-04        PM2.5   29.233333
10    2026-07-04     humidity   71.000000
11    2026-07-05         PM10   55.700000

## Запис в lake у золоту зону

In [69]:
lake_path("gold", "avg_by_city_metric")

'shudria_oleh/gold/avg_by_city_metric/avg_by_city_metric.parquet'

In [70]:
lake_path("gold", "pm25_exceedances")

'shudria_oleh/gold/pm25_exceedances/pm25_exceedances.parquet'

In [71]:
lake_path("gold", "daily_trend")

'shudria_oleh/gold/daily_trend/daily_trend.parquet'

In [72]:
write_parquet(avg_by_city_metric, "gold", "avg_by_city_metric")
write_parquet(pm25_exceedances, "gold", "pm25_exceedances")
write_parquet(daily_trend, "gold", "daily_trend")

## Фінальна перевірка структури

Повний лістинг власного префікса: зони `bronze`, `silver`, `gold`.

In [73]:
for b in lake.list_blobs(name_starts_with=STUDENT):
    print(b.name, b.size, b.last_modified)

shudria_oleh/bronze/readings/readings.parquet 4963 2026-07-27 20:06:44+00:00
shudria_oleh/bronze/sensors/sensors.parquet 4073 2026-07-27 20:06:44+00:00
shudria_oleh/bronze/stations/stations.parquet 4760 2026-07-27 20:06:44+00:00
shudria_oleh/gold/avg_by_city_metric/avg_by_city_metric.parquet 2956 2026-07-27 20:06:46+00:00
shudria_oleh/gold/daily_trend/daily_trend.parquet 2529 2026-07-27 20:06:46+00:00
shudria_oleh/gold/pm25_exceedances/pm25_exceedances.parquet 2903 2026-07-27 20:06:46+00:00
shudria_oleh/silver/_quality_report.json 1550 2026-07-27 20:02:50+00:00
shudria_oleh/silver/_tier_probe.json 208 2026-07-27 19:59:59+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=01/part.parquet 4535 2026-07-27 20:06:45+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=02/part.parquet 4474 2026-07-27 20:06:45+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=03/part.parquet 4486 2026-07-27 20:06:45+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=04/part.parquet 4524 2026-07-27 20:06:45+00:00
shudria_oleh/silver/readings/year=2026/month=07/day=05/part.parquet 4425 2026-07-27 20:06:46+00:00
shudria_oleh/silver/sensors/sensors.parquet 2773 2026-07-27 20:06:45+00:00
shudria_oleh/silver/stations/stations.parquet 3441 2026-07-27 20:06:44+00:00
shudria_oleh/stations/stations.parquet 4724 2026-07-26 14:22:36+00:00

# Висновок

У сирих даних виявлено шістнадцять типів дефектів: три різні формати дат, десяткові коми замість крапок, непослідовні написання міст, країн, метрик та одиниць виміру, повні дублікати рядків і дублікати за ключем, посилання на неіснуючий сенсор `SN999`, від'ємні та аномально великі значення, а також пропуски в датах і вимірах.

Усі дефекти усунено в зоні Silver: типи приведено явними форматами з каскадним парсингом дат (`%Y-%m-%d`, потім `%d-%m-%Y`), категорії нормалізовано за словниками з подальшою перевіркою їхньої повноти, некоректні записи відфільтровано, а пропущені одиниці виміру відновлено за метрикою сенсора. Аномалію `5000 µg/m3` для PM2.5 не видалено, а позначено прапорцем `is_outlier` і виключено лише на рівні агрегатів Gold, щоб факт виміру залишився доступним для аудиту.

З 23 сирих вимірів у Silver залишилося 18, з них у побудові вітрин Gold бере участь 17.

# Додаткове завдання

## Звіт про якість даних

Під час очищення в Silver кожен фільтр записує в `QUALITY_LOG`, скільки рядків він відкинув і з якої причини. Числа збираються автоматично, а не проставляються вручну: якщо вхідні дані зміняться, звіт оновиться сам.

Результат зберігається у `shudria_oleh/silver/_quality_report.json`. Підкреслення на початку імені позначає службовий файл, який не є таблицею даних.

In [74]:
quality_report = {
    "student": STUDENT,
    "generated_at_utc": INGESTED_AT_UTC.isoformat(),
    "rows_in_bronze": {table: len(dfs[table]) for table in TABLES},
    "rows_in_silver": {
        "stations": len(df_stations_silver),
        "sensors": len(df_sensors_silver),
        "readings": len(df_readings_silver),
    },
    "steps": QUALITY_LOG,
}

report_path = f"{STUDENT}/silver/_quality_report.json"

lake.upload_blob(
    name=report_path,
    data=json.dumps(quality_report, ensure_ascii=False, indent=2).encode("utf-8"),
    overwrite=True,
)

print(report_path)
print(json.dumps(quality_report, ensure_ascii=False, indent=2))

shudria_oleh/silver/_quality_report.json
{
  "student": "shudria_oleh",
  "generated_at_utc": "2026-07-27T20:06:43.256724+00:00",
  "rows_in_bronze": {
    "stations": 7,
    "sensors": 8,
    "readings": 23
  },
  "rows_in_silver": {
    "stations": 6,
    "sensors": 8,
    "readings": 18
  },
  "steps": [
    {
      "table": "stations",
      "reason": "дублікати за station_id",
      "rows_before": 7,
      "rows_dropped": 1,
      "rows_after": 6
    },
    {
      "table": "sensors",
      "reason": "station_id відсутній у Silver-таблиці stations",
      "rows_before": 8,
      "rows_dropped": 0,
      "rows_after": 8
    },
    {
      "table": "readings",
      "reason": "sensor_id відсутній у Silver-таблиці sensors",
      "rows_before": 23,
      "rows_dropped": 1,
      "rows_after": 22
    },
    {
      "table": "readings",
      "reason": "status не дорівнює ok (error або calibrating)",
      "rows_before": 22,
      "rows_dropped": 2,
      "rows_after": 20
    },
    {
      "table": "readings",
      "reason": "value порожнє або від'ємне",
      "rows_before": 20,
      "rows_dropped": 0,
      "rows_after": 20
    },
    {
      "table": "readings",
      "reason": "measured_at не розпізнано як дату",
      "rows_before": 20,
      "rows_dropped": 1,
      "rows_after": 19
    },
    {
      "table": "readings",
      "reason": "повні дублікати рядків",
      "rows_before": 19,
      "rows_dropped": 1,
      "rows_after": 18
    }
  ]
}

## Рівень доступу Cool

Переводимо `bronze/stations/stations.parquet` з рівня `Hot` на `Cool`.

**Чому це доцільно для Bronze.** Зона Bronze за призначенням є холодним архівом: вона пишеться один раз під час завантаження і читається лише тоді, коли треба перебудувати Silver або провести аудит походження даних. У самому конвеєрі кожен блоб Bronze читається рівно один раз за прогін. Рівень `Cool` коштує дешевше за зберігання і дорожче за читання, тому для об'єкта з таким профілем доступу він вигідніший за `Hot`.

**Чому не для Silver і Gold.** Ці зони читають при кожній побудові вітрин і кожен аналітик, який працює з даними. Для них підвищена плата за операції читання перекрила б економію на зберіганні.

In [75]:
COOL_BLOB = lake_path("bronze", "stations")
blob_client = lake.get_blob_client(COOL_BLOB)

blob_client.set_standard_blob_tier("Cool")

props = blob_client.get_blob_properties()
print(COOL_BLOB)
print(f"  рівень доступу: {props.blob_tier}")
print(f"  змінено: {props.blob_tier_change_time}")

shudria_oleh/bronze/stations/stations.parquet
  рівень доступу: Cool
  змінено: 2026-07-27 20:06:46+00:00